K8SPG-145 PG db 1.1.0 release preps
percona/percona-helm-charts pull request #104
Opened 2021-11-30 12:12 UTC by cap1984

2021-12-06 19:46 UTC, tplavcic approved these changes

2021-12-06 20:48 UTC, hors requested changes

2021-12-06 20:48 UTC, hors commented on charts/pg-db/README.md
> +| `pmm.image.tag`                     | PMM Container image tag                                       | `2.21.0`                              |
Maybe we need to use 2.24.0 or 2.23.0

2021-12-06 20:48 UTC, hors commented on charts/pg-db/README.md
> +| `secrets.name`            | Database secrets object name. Object will be autogenerated if the name is not explicitly specified       |`<cluster_name>-users-secrets`|
```suggestion
| `secrets.name`            | Database secrets object name. Object will be autogenerated if the name is not explicitly specified       |`<cluster_name>-users`|
```

2021-12-06 20:48 UTC, hors commented on charts/pg-db/templates/user-secret.yaml
> +  name: {{ include "pg-database.fullname" $ }}-users-secret
```suggestion
  name: {{ include "pg-database.fullname" $ }}-users
```

2021-12-07 07:44 UTC, cap1984 commented on charts/pg-db/README.md
> +| `secrets.name`            | Database secrets object name. Object will be autogenerated if the name is not explicitly specified       |`<cluster_name>-users-secrets`|
done

2021-12-07 07:44 UTC, cap1984 commented on charts/pg-db/README.md
> +| `pmm.image.tag`                     | PMM Container image tag                                       | `2.21.0`                              |
done

2021-12-07 07:45 UTC, cap1984 commented on charts/pg-db/templates/user-secret.yaml
> +  name: {{ include "pg-database.fullname" $ }}-users-secret
done

2021-12-07 07:47 UTC, hors approved these changes

2021-12-07 14:09 UTC, merged