fix: quote namespace in pxc-operator deploy
percona/percona-helm-charts pull request #111
Opened 2022-01-13 15:36 UTC by pauliusm

When trying to install `pxc-operator` in number-only namespace, e.g.
```
helm -n 7129496 install my-operator percona/pxc-operator
```
Helm fails with cryptic error:
```
Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 7, error found in #10 byte of ...|,"value":7129496},{"|..., bigger context ...|rator"],"env":[{"name":"WATCH_NAMESPACE","value":7129496},{"name":"POD_NAME","valueFrom":{"fieldRef"|...
```
Quoting namespace will fix errors like that.

2022-03-25 16:38 UTC, pauliusm commented
Anyone here?

2022-05-09 08:56 UTC, hors commented
> Anyone here?

Hi, thanks for PR. We will check it soon.

2022-05-10 14:52 UTC, tplavcic requested changes

2022-05-10 14:52 UTC, tplavcic commented on charts/pxc-db/production-values.yaml
> +crVersion: 1.10.1
Please revert this to 1.10.0 and just bump the chart version to 1.10.1 since the operator version is staying the same.

2022-05-10 14:52 UTC, tplavcic commented on charts/pxc-db/values.yaml
> +crVersion: 1.10.1
Please leave this at 1.10.0 and just bump the chart version to 1.10.1.

2022-05-10 14:52 UTC, tplavcic commented on charts/pxc-operator/Chart.yaml
> +appVersion: 1.10.1
Please leave this at 1.10.0 and just bump the chart version to 1.10.1 because the operator version stays the same.

2022-05-10 14:52 UTC, tplavcic commented on charts/pxc-operator/Chart.yaml
> +version: 1.10.1
This should be ok.

2022-05-10 14:52 UTC, tplavcic commented on charts/pxc-operator/crds/crd.yaml
> +    - name: v1-10-1
Please revert this since it's not related to the helm chart directly.

2022-05-12 08:13 UTC, pauliusm commented
@tplavcic addressed all your comments, pls re-review.

2022-05-13 07:02 UTC, tplavcic requested changes

2022-05-13 07:02 UTC, tplavcic commented on charts/pxc-db/README.md
> +helm install my-db percona/pxc-db --version 1.10.1 --namespace my-namespace
This change should be in `pxc-operator` directory, not in `pxc-db`.

2022-05-27 11:31 UTC, tplavcic approved these changes

2022-05-27 11:31 UTC, merged

2022-05-27 11:32 UTC, tplavcic commented
@pauliusm Thank you very much for the contribution, it is merged now!