Additional image pull attributes
percona/percona-helm-charts pull request #124
Opened 2022-03-09 21:28 UTC by agelwarg

In an airgap environment, we need to set the imagePullPolicy to Never for images.  This PR allows us to set it for the missed images, as well as the imagePullSecrets.

2022-03-09 21:28 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-helm-charts?pullRequest=124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-helm-charts?pullRequest=124) before we can accept your contribution.<br/><hr/>**Adam Gelwarg** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-helm-charts?pullRequest=124) it.</sub>

2022-05-09 08:54 UTC, hors requested changes

2022-05-09 08:54 UTC, hors commented on charts/pxc-db/templates/cluster.yaml
> +    {{- if $logcollector.imagePullPolicy }}
@agelwarg please add all these options to https://github.com/percona/percona-helm-charts/blob/main/charts/pxc-db/README.md

also please check 
charts/pxc-db/values.yaml
charts/pxc-db/production-values.yaml

2022-05-10 12:26 UTC, tplavcic requested changes
Please bump the chart version here: https://github.com/percona/percona-helm-charts/blob/main/charts/pxc-db/Chart.yaml#L6

2022-05-16 10:49 UTC, merged

2022-05-16 10:57 UTC, tplavcic commented
@agelwarg Thank you very much for the contribution! It has now been merged and available in pxc-db chart v1.10.2.