K8SPXC-1048: fixing sidecarVolumes in pxc-db chart - Miklos Gergye
percona/percona-helm-charts pull request #147
Opened 2022-06-22 17:09 UTC by mgergye

Adding sidecarVolume support to the pxc-db, as it is already supported by the pxc-operator

Fixes K8SPXC-1048 (broken StatefulSet due a sidecarVolume)

2022-06-22 17:22 UTC, tplavcic commented
Thank you for the contribution! Could you please bump the chart version and then the tests should pass, after that we will review/check it a bit it and merge it.

2022-07-01 07:15 UTC, tplavcic requested changes
Please fix my suggestions and we can merge it.
Also it seems we are missing `sidecarPVCs` option so if you wish you can add it also and if you don't have time I will add it after merge-ing this PR.

2022-07-01 07:15 UTC, tplavcic commented on charts/pxc-db/templates/cluster.yaml
> +{{ $pxc.sidecarVolumes | toYaml | indent 6 }}
```suggestion
{{ $haproxy.sidecarVolumes | toYaml | indent 6 }}
```

2022-07-01 07:15 UTC, tplavcic commented on charts/pxc-db/templates/cluster.yaml
> +{{ $pxc.sidecarVolumes | toYaml | indent 6 }}
```suggestion
{{ $proxysql.sidecarVolumes | toYaml | indent 6 }}
```

2022-07-01 07:28 UTC, tplavcic approved these changes

2022-07-01 07:30 UTC, egegunes approved these changes
LGTM

2022-07-01 07:31 UTC, merged

2022-07-01 07:33 UTC, tplavcic commented
Thank you, this was merged and I will create another PR to add `sidecarPVCs` option.