typo percon -> percona
percona/percona-helm-charts pull request #201
Opened 2023-02-24 22:12 UTC by michaelcoburn

2023-02-24 22:12 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-helm-charts?pullRequest=201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-helm-charts?pullRequest=201) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-helm-charts?pullRequest=201) it.</sub>

2023-02-25 01:50 UTC, gen1us2k submitted a review, later dismissed

2023-02-27 11:01 UTC, denisok commented
@gen1us2k could you please cherry-pick this one into your PR, so we would go faster ?

2023-02-28 08:11 UTC, denisok commented
@michaelcoburn could you please bump chart version to 1.2 ?
https://github.com/percona/percona-helm-charts/blob/main/charts/pmm/Chart.yaml#L5

2023-03-02 16:35 UTC, michaelcoburn commented
@denisok done :+1:

2023-03-02 16:48 UTC, denisok commented
strange linter is not happy, probably 1.2.0 and if not happy again "1.2.0"

2023-03-03 13:19 UTC, denisok requested changes

2023-03-03 13:19 UTC, denisok commented on charts/pmm/Chart.yaml
> +version: 1.2
```suggestion
version: 1.2.0
```

2023-03-03 13:20 UTC, denisok approved these changes

2023-03-03 13:23 UTC, tplavcic approved these changes

2023-03-03 13:23 UTC, merged