K8SPG-597 - Update PG operator chart for 2.4.0 release
percona/percona-helm-charts pull request #342
Opened 2024-06-27 14:38 UTC by jvpasinatto

2024-06-28 16:08 UTC, tplavcic requested changes

2024-06-28 16:08 UTC, tplavcic commented on charts/pg-db/README.md
> +| `image`                     | Postgres image                                                  | `percona/percona-postgresql-operator:2.4.0-ppg16-postgres`  |
please use the image from the cr.yaml

2024-06-28 16:08 UTC, tplavcic commented on charts/pg-db/README.md
> +| `backups.pgbackrest.image`                     | Set this variable if you need to use a custom pgBackrest image                                        | `percona/percona-postresql-operator:2.4.0-pp
please use the image from the cr.yaml

2024-06-28 16:08 UTC, tplavcic commented on charts/pg-db/README.md
>  | `proxy.pgBouncer.image`                     | Set this variable if you need to use a custom pgbouncer image                                        | `percona/percona-postresql-operator:1.4.0-ppg14-
please fix the pgbouncer image

2024-07-02 07:55 UTC, tplavcic requested changes

2024-07-02 07:55 UTC, tplavcic commented on charts/pg-db/values.yaml
> +#   syncPeriodSeconds: 10 # default: 10
Let's remove the `# default: 10` part

2024-07-02 07:55 UTC, tplavcic commented on charts/pg-db/values.yaml
> +#   leaderLeaseDurationSeconds: 30 # default: 30
Let's remove the `# default: 30` part

2024-07-02 08:19 UTC, ptankov approved these changes

2024-07-02 12:42 UTC, tplavcic approved these changes

2024-07-02 12:43 UTC, merged