K8SPXC-400 fix and more updates for PXC 1.6.0 release
percona/percona-helm-charts pull request #35
Opened 2020-10-12 14:01 UTC by tplavcic

2020-10-12 14:33 UTC, cap1984 approved these changes

2020-10-13 07:58 UTC, delgod requested changes

2020-10-13 07:58 UTC, delgod commented on charts/pxc-db/README.md
>  | `haproxy.persistence.size` | Sets K8S persistent storage size for all HAProxy Pods | `8Gi`                      |
I believe these options added by mistake, haproxy is stateless and shouldn't have persistence options

2020-10-13 08:45 UTC, delgod approved these changes

2020-10-13 14:00 UTC, cap1984 approved these changes

2020-10-15 07:17 UTC, merged