Update README.md
percona/percona-helm-charts pull request #360
Opened 2024-08-18 08:52 UTC by mohammed6688

fix the backup object documentation issue

2024-08-18 08:52 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-helm-charts?pullRequest=360) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-helm-charts?pullRequest=360) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-helm-charts?pullRequest=360) it.</sub>

2024-08-19 07:06 UTC, tplavcic approved these changes

2024-08-19 07:08 UTC, tplavcic requested changes
Please bump the chart version, it is needed even for README file updates.

2024-08-19 07:32 UTC, mohammed6688 commented
@tplavcic I have updated the helm chart version

2024-08-20 14:39 UTC, jvpasinatto approved these changes

2024-08-20 14:40 UTC, merged