K8SPXC-1363 - Update PXC operator chart for 1.15.0 release
percona/percona-helm-charts pull request #362
Opened 2024-08-19 17:27 UTC by jvpasinatto

2024-08-20 05:16 UTC, eleo007 approved these changes

2024-08-20 06:25 UTC, tplavcic requested changes

2024-08-20 06:25 UTC, tplavcic commented on charts/pxc-db/values.yaml
> +#   image: "perconalab/percona-xtradb-cluster-operator:1.15.0"
maybe don't mention `perconalab` images, even if it is commented, better use `percona`

2024-08-21 11:40 UTC, tplavcic approved these changes

2024-08-21 11:42 UTC, eleo007 approved these changes

2024-08-21 11:44 UTC, merged