Allow podAnnotations via helm values for Postgres operator
percona/percona-helm-charts pull request #364
Opened 2024-08-28 07:17 UTC by RobKenis

This allows users to set annotations on the pods for example for Prometheus.

2024-08-29 07:06 UTC, tplavcic requested changes
Please bump the chart version and update the README file.
Thanks!

2024-08-30 06:50 UTC, RobKenis commented
> Please bump the chart version and update the README file. Thanks!

Hi @tplavcic 

I have updated the README and the Chart version.

2024-08-30 07:24 UTC, tplavcic approved these changes

2024-08-30 13:13 UTC, jvpasinatto approved these changes

2024-08-30 13:13 UTC, merged

2024-08-30 14:35 UTC, tplavcic commented
@RobKenis Thank you for the nice contribution! ;)