K8SPSMDB-1098 - Update psmdb-operator chart for 1.17.0 release
percona/percona-helm-charts pull request #367
Opened 2024-09-02 12:17 UTC by jvpasinatto

2024-09-06 13:27 UTC, tplavcic approved these changes

2024-09-09 14:34 UTC, eleo007 approved these changes

2024-09-09 14:36 UTC, tplavcic requested changes
In the readme I wouldn't call them `PSMDB essential users` but instead `PSMDB operator system users`, also for the plain "users" maybe mention that these are Application users.

2024-09-10 07:50 UTC, tplavcic approved these changes

2024-09-10 11:24 UTC, merged