K8SPSMDB-277 GCP Marketplace bundle for PSMDB
percona/percona-helm-charts pull request #41
Opened 2020-11-12 20:32 UTC by cap1984

2020-11-17 18:25 UTC, tplavcic requested changes

2020-11-17 18:25 UTC, tplavcic commented on charts/gcp-marketplace/psmdb-operator/README.md
> +could be foud [here](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/users.html)
`foud` -> `found

2020-11-18 09:40 UTC, cap1984 commented on charts/gcp-marketplace/psmdb-operator/README.md
> +could be foud [here](https://www.percona.com/doc/kubernetes-operator-for-psmongodb/users.html)
done

2020-11-18 14:03 UTC, hors approved these changes

2020-11-18 14:08 UTC, merged